"""Research Copilot — product-facing AI research interface."""

from __future__ import annotations

import streamlit as st

from .client import PRODUCT_NAME, chat_completion, get_copilot_status, is_copilot_available
from .context import build_messages
from .prompts import QUICK_PROMPTS, RISK_COPILOT_SYSTEM


def render_sidebar_settings():
    """Minimal product status — no provider/key details."""
    status = get_copilot_status()
    if status == "Online":
        st.markdown(f"**Intelligence Engine** · 🟢 {status}")
    else:
        st.markdown(f"**Intelligence Engine** · 🔴 {status}")


def _init_chat_state():
    if "copilot_messages" not in st.session_state:
        st.session_state.copilot_messages = []


def _append_message(role: str, content: str):
    st.session_state.copilot_messages.append({"role": role, "content": content})


def _run_prompt(user_text: str):
    messages = build_messages(st.session_state, user_text, RISK_COPILOT_SYSTEM)

    with st.spinner("Analyzing scenario context..."):
        result = chat_completion(messages, temperature=0.35)

    if result["error"] and not result["content"]:
        _append_message("assistant", result["error"])
        return

    _append_message("assistant", result["content"])


def render():
    _init_chat_state()

    st.markdown('<div class="st-section-label">Research Copilot</div>', unsafe_allow_html=True)
    st.markdown(
        """
Ask research questions about your **active scenario**, **factor exposures**, or **alternative data**.
Responses are generated by the Shocktail Intelligence Engine and grounded in live platform data.
        """
    )

    if not is_copilot_available():
        st.info("Research Copilot is starting up. Please check back shortly.")

    st.markdown("**Research templates**")
    labels = {
        "executive_summary": "Executive Summary",
        "sector_memo": "Sector Memo",
        "alt_data_brief": "Alt Data Brief",
        "ic_briefing": "IC Briefing",
        "risk_actions": "Risk Actions",
    }
    cols = st.columns(5)
    for i, (key, prompt_text) in enumerate(QUICK_PROMPTS.items()):
        if cols[i].button(labels.get(key, key), key=f"quick_{key}", disabled=not is_copilot_available()):
            _append_message("user", prompt_text)
            _run_prompt(prompt_text)
            st.rerun()

    for msg in st.session_state.copilot_messages:
        with st.chat_message(msg["role"]):
            st.markdown(msg["content"])

    if prompt := st.chat_input(
        "Ask a research question...",
        disabled=not is_copilot_available(),
    ):
        _append_message("user", prompt)
        _run_prompt(prompt)
        st.rerun()

    if st.session_state.copilot_messages and st.button("Clear session"):
        st.session_state.copilot_messages = []
        st.rerun()

    with st.expander("Analysis context", expanded=False):
        from .context import build_risk_context
        st.caption(f"Data grounding layer · {PRODUCT_NAME}")
        st.code(build_risk_context(st.session_state), language=None)